package frc.robot.lib;

/**
 * The following class exists to stop crashes at runtime trying to access missing/mistyped
 * pathweaver files (#145). This class is autogenerated at compile, containing public strings for
 * all of the files in the pathweaver output directory. These public strings are to be used with
 * driveRelativeWaypoints(pathname) in Auto.java instead of directly referring to the pathweaver
 * files.
 */
public class AutoPaths {

    // DO NOT CHANGE THIS FILE!
    // THIS ENTIRE FILE WILL BE REGENERATED BY GRADLE AT COMPILE TIME!
    public static final String k2ball = "2ball.wpilib.json";
    public static final String k3ballA = "3ballA.wpilib.json";
    public static final String k3ballB = "3ballB.wpilib.json";
    public static final String k3ballC = "3ballC.wpilib.json";
    public static final String k3ballD = "3ballD.wpilib.json";

}
