name: Java CI

on:
  push:
    branches: [master]
    paths:
      - "**.java"
      - "**.gradle"
      - "**.json"
      - "**.yml"
  pull_request:
    paths:
      - "**.java"
      - "**.gradle"
      - "**.json"
      - "**.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    # Contains necessary cross-build tools and correct JDK for building applications targeted at the roboRIO
    # https://hub.docker.com/r/wpilib/roborio-cross-ubuntu
    # container: wpilib/roborio-cross-ubuntu:2022-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          # Fetch depth 0 will fetch history for all branches and tags
          # This is needed because part of the Gradle build process compares to origin/master
          fetch-depth: 0

      - name: Validate Gradle wrapper
        # Validate checksum of Gradle wrapper JAR
        uses: gradle/wrapper-validation-action@v1

      # Not required if using the roboRIO cross-compile container
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: "11"

      - name: Compile and test with Gradle
        uses: burrunan/gradle-cache-action@v1
        # Caches Gradle build and dependencies whilst running tests
        with:
          # If you have multiple jobs, use distinct job-id in in case you want to split caches
          # For instance, jobs with different JDK versions can't share caches
          # RUNNER_OS is added to job-id automatically
          job-id: jdk11
          # Specifies arguments for Gradle execution
          # If arguments is missing or empty, then Gradle is not executed
          arguments: test
          gradle-version: wrapper
